export const errors = {
	NOT_FOUND: 'NOT_FOUND',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	GRAPH_NODE_NOT_FOUND: 'GRAPH_NODE_NOT_FOUND',
	PLACE_NOT_FOUND: 'PLACE_NOT_FOUND',
	GEOCODER_UNAVAILABLE: 'GEOCODER_UNAVAILABLE',
	GRAPH_CONNECTIVITY_GAP: 'GRAPH_CONNECTIVITY_GAP'
};